version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn war:exploded
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
      - mv target/ROOT .
artifacts:
  type: zip
  files:
    - 'ROOT/WEB-INF/classes/application.properties'
    - 'ROOT/WEB-INF/classes/com/omkarsh/projecttemplates/*'
    - 'ROOT/WEB-INF/classes/com/omkarsh/configuration/*'
    - 'ROOT/WEB-INF/classes/com/omkarsh/controller/*'
    - 'ROOT/WEB-INF/classes/com/omkarsh/dao/*'
    - 'ROOT/WEB-INF/classes/com/omkarsh/service/*'
    - 'ROOT/WEB-INF/classes/com/entity/*'
    - 'ROOT/WEB-INF/lib/*'
    - 'ROOT/views/*'
    - 'ROOT/WEB-INF/classes/static/*'

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    